name: Build Android APK (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -q CameraManagerAndroid_Kotlin_v2.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Download Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip -O /tmp/gradle.zip
          unzip -q /tmp/gradle.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH

      - name: Build debug APK
        working-directory: ./CameraManagerAndroid
        run: gradle assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: CameraManagerAndroid/app/build/outputs/apk/debug/*.apk
